backend:
  name: github
  repo: SoumyaK4/SoumyaK4
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:

  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss Z"

      - label: "Categories"
        name: "category"
        widget: "list"
        default: [blog]

      - label: "Tags"
        name: "tag"
        widget: "list"
        default: [blog]
        required: false

      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Blog", value: "blog" }
          - { label: "Project", value: "project" }
        default: "blog"

      - label: "Permalink"
        name: "permalink"
        widget: "string"
        default: "Blog/"
        required: false

      - label: "Pinned"
        name: "pin"
        widget: "boolean"
        default: false

      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - label: "Image File"
            name: "path"
            widget: "image"
            required: false

          - label: "LQIP"
            name: "lqip"
            widget: "string"
            required: false

      - label: "Body"
        name: "body"
        widget: "markdown"


  - name: "tabs"
    label: "Tabs"
    folder: "_tabs"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Icon"
        name: "icon"
        widget: "string"

      - label: "Order"
        name: "order"
        widget: "number"

      - label: "Permalink"
        name: "permalink"
        widget: "string"

      - label: "Layout"
        name: "layout"
        widget: "string"
        default: "page"

      - label: "Body"
        name: "body"
        widget: "markdown"
